services:
  server:
    build: ./server
    ports:
      - "3001:3001"
    env_file:
      - ./server/.env

  frontend:
    build: ./my-react-router-app
    ports:
      - "5173:80" # map host 3000 → container's port 80
