services:
  server:
    build:
      context: ./server
    ports:
      - "3001:3001"
    env_file:
      - ./server/.env
  frontend:
    build:
      context: ./my-react-router-app
    ports:
      - "5173:5173"
